insert INTO conferences (description)values('Writing Fast Tests Against Enterprise Rails 60min*')
insert INTO conferences (description)values('¡   Overdoing it in Python 45min')
insert INTO conferences (description)values('Lua for the Masses 30min')
insert INTO conferences (description)values('Ruby Errors from Mismatched Gem Versions 45min')
insert INTO conferences (description)values('Common Ruby Errors 45min')
insert INTO conferences (description)values('Rails for Python Developers lightning')
insert INTO conferences (description)values('Communicating Over Distance 60min')
insert INTO conferences (description)values('Accounting-Driven Development 45min')
insert INTO conferences (description)values('Woah 30min')
insert INTO conferences (description)values('Sit Down and Write 30min')
insert INTO conferences (description)values('Pair Programming vs Noise 45min')
insert INTO conferences (description)values('Rails Magic 60min')
insert INTO conferences (description)values('Ruby on Rails: Why We Should Move On 60min')
insert INTO conferences (description)values('Clojure Ate Scala (on my project) 45min')
insert INTO conferences (description)values('Programming in the Boondocks of Seattle 30min')
insert INTO conferences (description)values('Ruby vs. Clojure for Back-End Development 30min')
insert INTO conferences (description)values('Ruby on Rails Legacy App Maintenance 60min')
insert INTO conferences (description)values('A World Without HackerNews 30min')
insert INTO conferences (description)values('User Interface CSS in Rails Apps 30min')
